version: '3.8'
services:
  frontend:
    image: frontend-image
    networks:
      - home-media-network
  backend:
    image: backend-image
    networks:
      - home-media-network
    ports:
      # removed the external port mapping
    # 3123:3001

networks:
  home-media-network:
    driver: bridge